/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUSUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import BUSUI.*;
import BUSCONTROL.*;
import BUSDOMAIN.*;
import java.awt.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class RefundCancelPanel extends javax.swing.JPanel {

    MaintainStaffControl staffControl = new MaintainStaffControl();
    MaintainJobpositionControl jobControl = new MaintainJobpositionControl();
    MaintainPaymenttypeControl paymentControl = new MaintainPaymenttypeControl();
    MaintainDriverlistControl driverlistControl = new MaintainDriverlistControl();
    MaintainTransControl transControl = new MaintainTransControl();
    private Staff currentStaff;

    public RefundCancelPanel(Counter ds, Staff s) {
        currentStaff = s;
        initComponents();
        jbtUpdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtfSearch = new javax.swing.JTextField();
        jlbSearch = new javax.swing.JLabel();
        jbtUpdate = new javax.swing.JButton();
        jlbCurrentStaff = new javax.swing.JLabel();
        jlbCurrentStaffIDC = new javax.swing.JLabel();
        jlbTransID = new javax.swing.JLabel();
        jlbStaffID = new javax.swing.JLabel();
        jlbCounterID = new javax.swing.JLabel();
        jlbCustomerName = new javax.swing.JLabel();
        jlbTransDate = new javax.swing.JLabel();
        jlbTotal = new javax.swing.JLabel();
        jlbDiscountType = new javax.swing.JLabel();
        jlbDiscountAMT = new javax.swing.JLabel();
        jlbPaymentType = new javax.swing.JLabel();
        jlbStatus = new javax.swing.JLabel();
        jtfTransDate = new javax.swing.JTextField();
        jtfTransID = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();
        jtfStaffID = new javax.swing.JTextField();
        jtfDiscounttype = new javax.swing.JTextField();
        jtfPaymenttype = new javax.swing.JTextField();
        jtfDiscountAmount = new javax.swing.JTextField();
        jtfCounterID = new javax.swing.JTextField();
        jtfCustName = new javax.swing.JTextField();
        jtfStatus = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retrieve/Refund Transaction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        jtfSearch.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSearchKeyTyped(evt);
            }
        });

        jlbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xlImages/search.png"))); // NOI18N
        jlbSearch.setToolTipText("Search");
        jlbSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbSearchMouseClicked(evt);
            }
        });

        jbtUpdate.setBackground(new java.awt.Color(192, 57, 43));
        jbtUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jbtUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtUpdate.setText("Refund");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        jlbCurrentStaff.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlbCurrentStaff.setText("Current Staff ID: ");

        jlbCurrentStaffIDC.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jlbTransID.setText("Transaction ID :");

        jlbStaffID.setText("Staff ID :");

        jlbCounterID.setText("Counter ID :");

        jlbCustomerName.setText("Customer Name:");

        jlbTransDate.setText("Transaction Date :");

        jlbTotal.setText("Total Payment :");

        jlbDiscountType.setText("Discount Type :");

        jlbDiscountAMT.setText("Discount Amount :");

        jlbPaymentType.setText("Payment Type :");

        jlbStatus.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlbStatus.setText("Status :");

        jtfTransDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTransDate.setEnabled(false);

        jtfTransID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTransID.setEnabled(false);

        jtfTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTotal.setEnabled(false);

        jtfStaffID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfStaffID.setEnabled(false);

        jtfDiscounttype.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfDiscounttype.setEnabled(false);

        jtfPaymenttype.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfPaymenttype.setEnabled(false);

        jtfDiscountAmount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfDiscountAmount.setEnabled(false);

        jtfCounterID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCounterID.setEnabled(false);

        jtfCustName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCustName.setDragEnabled(true);
        jtfCustName.setEnabled(false);

        jtfStatus.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jtfStatus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfStatus.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlbTransID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbStaffID)
                                        .addComponent(jlbCounterID, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlbCustomerName)
                                    .addComponent(jlbStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfTransID)
                                        .addComponent(jtfStaffID)
                                        .addComponent(jtfCounterID)
                                        .addComponent(jtfCustName, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbTransDate)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbDiscountType)
                                        .addComponent(jlbTotal))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlbPaymentType)
                                        .addComponent(jlbDiscountAMT))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jlbCurrentStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbCurrentStaffIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtfTotal)
                        .addComponent(jtfDiscounttype)
                        .addComponent(jtfDiscountAmount)
                        .addComponent(jtfPaymenttype))
                    .addComponent(jtfTransDate, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSearch))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbCurrentStaffIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCurrentStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTransID)
                    .addComponent(jlbTransDate)
                    .addComponent(jtfTransID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTransDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStaffID)
                    .addComponent(jlbTotal)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCounterID)
                    .addComponent(jlbDiscountType)
                    .addComponent(jtfDiscounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCounterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCustomerName)
                    .addComponent(jlbDiscountAMT)
                    .addComponent(jtfDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPaymentType)
                            .addComponent(jtfPaymenttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jbtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed

    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jtfSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetterOrDigit(c) && jtfSearch.getText().length() < 6) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfSearchKeyTyped

    private void jlbSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSearchMouseClicked

        String id = jtfSearch.getText();
        Trans trans = transControl.selectRecord(id);

        if (trans != null) {

            jtfTransID.setText(trans.getTransid());
            jtfStaffID.setText(trans.getStaffid().getStaffid());
            jtfCounterID.setText(trans.getCounterid().getCounterid());
            jtfCustName.setText(trans.getCustname());
            jtfStatus.setText(trans.getPaidstatus());
            jtfTransDate.setText(trans.getTransdate().toString());
            jtfTotal.setText(trans.getTtlamount() + "");
            jtfDiscounttype.setText(trans.getDiscounttype());
            jtfDiscountAmount.setText(trans.getDiscountamount() + "");
            jtfPaymenttype.setText(trans.getPymtid().getPaymenttype());
            jlbCurrentStaffIDC.setText(currentStaff.getStaffid() + "-" + currentStaff.getStaffname());
            if (trans.getPaidstatus().equals("VOID")) {
                jbtUpdate.setVisible(false);
            } else {
                jbtUpdate.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID ", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jlbSearchMouseClicked

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to refund?", "Confirm Refund?",JOptionPane.WARNING_MESSAGE) == 0) {
            transControl.voidRecord(jtfTransID.getText());
            String id = jtfSearch.getText();
            Trans trans2 = transControl.selectRecord(id);
            jtfStatus.setText(trans2.getPaidstatus());
            JOptionPane.showMessageDialog(null, "Refund Amount : " + trans2.getTtlamount() + "", "Refund Complete", JOptionPane.INFORMATION_MESSAGE);
            jbtUpdate.setVisible(false);
        }
    }//GEN-LAST:event_jbtUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JLabel jlbCounterID;
    private javax.swing.JLabel jlbCurrentStaff;
    private javax.swing.JLabel jlbCurrentStaffIDC;
    private javax.swing.JLabel jlbCustomerName;
    private javax.swing.JLabel jlbDiscountAMT;
    private javax.swing.JLabel jlbDiscountType;
    private javax.swing.JLabel jlbPaymentType;
    private javax.swing.JLabel jlbSearch;
    private javax.swing.JLabel jlbStaffID;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JLabel jlbTransDate;
    private javax.swing.JLabel jlbTransID;
    private javax.swing.JTextField jtfCounterID;
    private javax.swing.JTextField jtfCustName;
    private javax.swing.JTextField jtfDiscountAmount;
    private javax.swing.JTextField jtfDiscounttype;
    private javax.swing.JTextField jtfPaymenttype;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JTextField jtfStatus;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfTransDate;
    private javax.swing.JTextField jtfTransID;
    // End of variables declaration//GEN-END:variables
}
