/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUSUI;

import BUSCONTROL.*;
import BUSCONTROL.MaintainJobpositionControl;
import BUSCONTROL.MaintainPaymenttypeControl;
import BUSCONTROL.MaintainStaffControl;
import BUSDOMAIN.*;
import BUSDOMAIN.Jobposition;
import BUSDOMAIN.Paymenttype;
import BUSDOMAIN.Staff;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author huiwe
 */
public class StaffManagementForm extends javax.swing.JPanel {

    MaintainStaffControl staffControl = new MaintainStaffControl();
    MaintainJobpositionControl jobControl = new MaintainJobpositionControl();
    MaintainPaymenttypeControl paymentControl = new MaintainPaymenttypeControl();
    MaintainDriverlistControl driverlistControl = new MaintainDriverlistControl();
    private ImageIcon imgPhoto;
    private String imageURL = "-";
    private final JFileChooser jfcPhoto = new JFileChooser();
    private String stf;
    private boolean duringCreate = false;
    JTextField jtfStartWorkDate = new JTextField();
    JTextField jtfLastWorkDate = new JTextField();
    UtilDateModel model = new UtilDateModel();
    UtilDateModel model2 = new UtilDateModel();
    Properties p = new Properties();
    Properties p2 = new Properties();
    JDatePanelImpl datePanel;
    JDatePanelImpl datePanel2;
    JDatePickerImpl datePicker;
    JDatePickerImpl datePicker2;
    Staff cs;
    Counter cc;
    public StaffManagementForm(Counter ds,Staff s) {
        cs=s;
        cc=ds;
        initComponents();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");
        p2.put("text.today", "Today");
        p2.put("text.month", "Month");
        p2.put("text.year", "Year");
        datePanel = new JDatePanelImpl(model, p);
        datePanel2 = new JDatePanelImpl(model2, p2);
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        datePicker2 = new JDatePickerImpl(datePanel2, new DateLabelFormatter());
        jbtAdd.setVisible(false);
        jbtRemove.setVisible(false);
        jbtResetPassword.setVisible(false);
        jbtUpdate.setVisible(false);
        calenderPanelstart.add(jtfStartWorkDate);
        jtfStartWorkDate.setEnabled(false);
        calenderPanelLast.add(jtfLastWorkDate);
        jtfLastWorkDate.setEnabled(false);
        jbtEndStaff.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        jlbStaffID = new javax.swing.JLabel();
        jtfStaffID = new javax.swing.JTextField();
        jtfStaffName = new javax.swing.JTextField();
        jlbStaffName = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jlbUsername = new javax.swing.JLabel();
        jtfSalary = new javax.swing.JTextField();
        jlbSalary = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jlbAddress = new javax.swing.JLabel();
        jlbBankType = new javax.swing.JLabel();
        jtfContactNum = new javax.swing.JTextField();
        jlbPosition = new javax.swing.JLabel();
        jcbBankType = new javax.swing.JComboBox();
        jpfPassword = new javax.swing.JPasswordField();
        jlbLastWorkDate = new javax.swing.JLabel();
        jlbSearch = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbAddStaff = new javax.swing.JLabel();
        jlbStartWorkDate = new javax.swing.JLabel();
        jlbEditStaff = new javax.swing.JLabel();
        jlIcon = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jbtAdd = new javax.swing.JButton();
        jlbNRIC = new javax.swing.JLabel();
        jlbContactNum = new javax.swing.JLabel();
        jbtRemove = new javax.swing.JButton();
        jtfNRIC = new javax.swing.JTextField();
        jlbAccNum = new javax.swing.JLabel();
        jtfAccNum = new javax.swing.JTextField();
        jtfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jbtResetPassword = new javax.swing.JButton();
        calenderPanelstart = new javax.swing.JPanel();
        calenderPanelLast = new javax.swing.JPanel();
        jbtEndStaff = new javax.swing.JButton();
        jbtDriverSchedulling = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtUpdate = new javax.swing.JButton();
        jlbClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jrbManager = new javax.swing.JCheckBox();
        jrbDriver = new javax.swing.JCheckBox();
        jrbSupervisor = new javax.swing.JCheckBox();
        jrbCounterClerk = new javax.swing.JCheckBox();

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbStaffID.setText("Staff ID:");
        ContentPanel.add(jlbStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, -1, -1));

        jtfStaffID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfStaffID.setEnabled(false);
        jtfStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStaffIDActionPerformed(evt);
            }
        });
        ContentPanel.add(jtfStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 95, 170, -1));

        jtfStaffName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfStaffName.setEnabled(false);
        jtfStaffName.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtfStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStaffNameActionPerformed(evt);
            }
        });
        jtfStaffName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfStaffNameKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 138, 170, -1));

        jlbStaffName.setText("Staff Name:");
        ContentPanel.add(jlbStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, -1, -1));

        jtfUsername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfUsername.setEnabled(false);
        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 178, 170, -1));

        jlbUsername.setText("Username:");
        ContentPanel.add(jlbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, -1, -1));

        jtfSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfSalary.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfSalary.setEnabled(false);
        jtfSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSalaryKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 287, 170, 30));

        jlbSalary.setText("Salary:");
        ContentPanel.add(jlbSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jlbPassword.setText("Password:");
        ContentPanel.add(jlbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jlbAddress.setText("Address:");
        ContentPanel.add(jlbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, -1, -1));

        jlbBankType.setText("Bank Type:");
        ContentPanel.add(jlbBankType, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 369, -1, 20));

        jtfContactNum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfContactNum.setEnabled(false);
        jtfContactNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContactNumKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 438, 166, -1));

        jlbPosition.setText("Position:");
        ContentPanel.add(jlbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 464, -1, -1));

        jcbBankType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MayBank", "CIMB", "Public Bank Berhad", "RHB Bank", "Hong Leong Bank", "AMMB Holdings", "United Overseas Bank (Malaysia)", "Bank Rakyat", "OCBC Bank (Malaysia)", "HSBC Bank Malaysia" }));
        jcbBankType.setEnabled(false);
        jcbBankType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBankTypeActionPerformed(evt);
            }
        });
        ContentPanel.add(jcbBankType, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 369, 170, -1));

        jpfPassword.setText("********");
        jpfPassword.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jpfPassword.setEnabled(false);
        ContentPanel.add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 217, 90, -1));

        jlbLastWorkDate.setText("Last Work Date:");
        ContentPanel.add(jlbLastWorkDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 331, -1, -1));

        jlbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xlImages/search.png"))); // NOI18N
        jlbSearch.setToolTipText("Search");
        jlbSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbSearchMouseClicked(evt);
            }
        });
        ContentPanel.add(jlbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 46, -1, -1));

        jlbEmail.setText("E-mail:");
        ContentPanel.add(jlbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 441, -1, -1));

        jlbAddStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xlImages/add_user.png"))); // NOI18N
        jlbAddStaff.setToolTipText("Add New Staff");
        jlbAddStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAddStaffMouseClicked(evt);
            }
        });
        ContentPanel.add(jlbAddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 46, -1, -1));

        jlbStartWorkDate.setText("Start Work Date:");
        ContentPanel.add(jlbStartWorkDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 290, -1, -1));

        jlbEditStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xlImages/edit.png"))); // NOI18N
        jlbEditStaff.setToolTipText("Edit Staff");
        jlbEditStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbEditStaffMouseClicked(evt);
            }
        });
        ContentPanel.add(jlbEditStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 46, -1, -1));

        jlIcon.setBackground(new java.awt.Color(255, 255, 255));
        jlIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        jlIcon.setOpaque(true);
        ContentPanel.add(jlIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 106, 152, 136));

        jtfEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfEmail.setEnabled(false);
        jtfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfEmailKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 438, 170, -1));

        jbtAdd.setBackground(new java.awt.Color(0, 153, 153));
        jbtAdd.setForeground(new java.awt.Color(255, 255, 255));
        jbtAdd.setText("Add");
        jbtAdd.setToolTipText("Add Staff Image");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        ContentPanel.add(jbtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 253, 66, -1));

        jlbNRIC.setText("NRIC:");
        ContentPanel.add(jlbNRIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 326, -1, -1));

        jlbContactNum.setText("Contact Number:");
        ContentPanel.add(jlbContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 441, -1, -1));

        jbtRemove.setBackground(new java.awt.Color(255, 0, 0));
        jbtRemove.setForeground(new java.awt.Color(255, 255, 255));
        jbtRemove.setText("Remove");
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });
        ContentPanel.add(jbtRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 253, 80, -1));

        jtfNRIC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfNRIC.setEnabled(false);
        jtfNRIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNRICKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfNRIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 326, 170, 25));

        jlbAccNum.setText("Account Number:");
        ContentPanel.add(jlbAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 403, -1, -1));

        jtfAccNum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfAccNum.setEnabled(false);
        jtfAccNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAccNumKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 400, 170, -1));

        jtfSearch.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSearchKeyTyped(evt);
            }
        });
        ContentPanel.add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 46, 156, -1));

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setOpaque(false);

        jtaAddress.setColumns(20);
        jtaAddress.setRows(5);
        jtaAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtaAddress.setEnabled(false);
        jtaAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaAddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtaAddress);

        ContentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 369, 170, 51));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*Default Password = 12345678");
        ContentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 245, -1, -1));

        jbtResetPassword.setBackground(new java.awt.Color(0, 204, 0));
        jbtResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        jbtResetPassword.setText("Reset");
        jbtResetPassword.setToolTipText("Reset Password to Default");
        jbtResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetPasswordActionPerformed(evt);
            }
        });
        ContentPanel.add(jbtResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 216, 80, -1));

        calenderPanelstart.setLayout(new java.awt.GridLayout(1, 0));
        ContentPanel.add(calenderPanelstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 287, 170, 26));

        calenderPanelLast.setLayout(new java.awt.GridLayout(1, 0));
        ContentPanel.add(calenderPanelLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 326, 87, 25));

        jbtEndStaff.setBackground(new java.awt.Color(255, 102, 0));
        jbtEndStaff.setForeground(new java.awt.Color(255, 255, 255));
        jbtEndStaff.setText("End Staff");
        jbtEndStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEndStaffActionPerformed(evt);
            }
        });
        ContentPanel.add(jbtEndStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 328, -1, -1));

        jbtDriverSchedulling.setBackground(new java.awt.Color(255, 51, 255));
        jbtDriverSchedulling.setForeground(new java.awt.Color(255, 255, 255));
        jbtDriverSchedulling.setText("Driver Schedulling");
        jbtDriverSchedulling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDriverSchedullingActionPerformed(evt);
            }
        });
        ContentPanel.add(jbtDriverSchedulling, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 72, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 171, 171));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GreyIcon/person.png"))); // NOI18N
        jLabel1.setText("View Staff");
        ContentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 304, -1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 4, 2));

        jbtUpdate.setBackground(new java.awt.Color(0, 153, 153));
        jbtUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtUpdate.setText("Create");
        jbtUpdate.setActionCommand("");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtUpdate);

        jlbClear.setBackground(new java.awt.Color(0, 153, 102));
        jlbClear.setForeground(new java.awt.Color(255, 255, 255));
        jlbClear.setText("Clear");
        jlbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbClearActionPerformed(evt);
            }
        });
        jPanel1.add(jlbClear);

        ContentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 498, 552, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(jrbManager);
        jrbManager.setText("Manager");
        jrbManager.setEnabled(false);
        jrbManager.setOpaque(false);
        jrbManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbManagerActionPerformed(evt);
            }
        });
        jPanel2.add(jrbManager);

        jrbDriver.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbDriver);
        jrbDriver.setText("Driver");
        jrbDriver.setEnabled(false);
        jPanel2.add(jrbDriver);

        buttonGroup1.add(jrbSupervisor);
        jrbSupervisor.setText("Supervisor");
        jrbSupervisor.setEnabled(false);
        jrbSupervisor.setOpaque(false);
        jrbSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSupervisorActionPerformed(evt);
            }
        });
        jPanel2.add(jrbSupervisor);

        buttonGroup1.add(jrbCounterClerk);
        jrbCounterClerk.setText("Counter Clerk");
        jrbCounterClerk.setEnabled(false);
        jrbCounterClerk.setOpaque(false);
        jrbCounterClerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCounterClerkActionPerformed(evt);
            }
        });
        jPanel2.add(jrbCounterClerk);

        ContentPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 464, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ContentPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtDriverSchedullingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDriverSchedullingActionPerformed
         DriverSchedulingMain f = new DriverSchedulingMain(cc,cs);
         ((Window) getRootPane().getParent()).dispose();
    }//GEN-LAST:event_jbtDriverSchedullingActionPerformed

    private void jbtEndStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEndStaffActionPerformed
        calenderPanelLast.removeAll();
        calenderPanelLast.add(datePicker2);
        calenderPanelLast.repaint();
        calenderPanelLast.revalidate();
        repaint();
    }//GEN-LAST:event_jbtEndStaffActionPerformed

    private void jbtResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetPasswordActionPerformed
        try {
            Staff chgStaffPW = staffControl.selectRecord(jtfStaffID.getText());
            chgStaffPW.setPassword("12345678");
            staffControl.updateRecord(chgStaffPW);
            JOptionPane.showMessageDialog(null, "Password has been reset!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Unable To Update Password"+ex.getMessage(), "Fail to reset", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtResetPasswordActionPerformed

    private void jtaAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaAddressKeyTyped

        char c = evt.getKeyChar();

        if (Character.isDefined(c) && jtaAddress.getText().length() < 199) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtaAddressKeyTyped

    private void jtfSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetterOrDigit(c) && jtfSearch.getText().length() < 6) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfSearchKeyTyped

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed

    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jtfAccNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAccNumKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfAccNum.getText().length() < 20) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfAccNumKeyTyped

    private void jtfNRICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNRICKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfNRIC.getText().length() < 12) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfNRICKeyTyped

    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
        jlIcon.setIcon(null);
        imageURL = "-";
    }//GEN-LAST:event_jbtRemoveActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        int result = jfcPhoto.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jfcPhoto.getSelectedFile();
            imageURL = file.getAbsolutePath();
            imgPhoto = new ImageIcon(imageURL);
            Image image = imgPhoto.getImage().getScaledInstance(129, 145, Image.SCALE_SMOOTH);
            imgPhoto.setImage(image);
            jlIcon.setIcon(imgPhoto);

            repaint();
        }
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jrbManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbManagerActionPerformed

    private void jtfEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmailKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDefined(c) && jtfEmail.getText().length() < 99) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfEmailKeyTyped

    private void jlbEditStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditStaffMouseClicked
        if (jtfStaffID.getText().equals("") || duringCreate) {
            JOptionPane.showMessageDialog(null, "Search for a Staff Before You Can Edit!!", "Search First", JOptionPane.ERROR_MESSAGE);
        } else {
            jbtEndStaff.setVisible(true);
            jtfStaffName.setEnabled(true);
            jtfUsername.setEnabled(true);
            jtfSalary.setEnabled(true);
            jtfNRIC.setEnabled(true);
            jtaAddress.setEnabled(true);
            jtfContactNum.setEnabled(true);
            jtfEmail.setEnabled(true);
            jtfSearch.setEnabled(true);
            jtfAccNum.setEnabled(true);
            jrbDriver.setEnabled(true);
            jrbCounterClerk.setEnabled(true);
            jrbSupervisor.setEnabled(true);
            jrbManager.setEnabled(true);
            jcbBankType.setEnabled(true);
            jbtAdd.setVisible(true);
            jbtRemove.setVisible(true);
            jbtUpdate.setText("Update");
            jbtUpdate.setVisible(true);
            jbtResetPassword.setVisible(true);
        }
    }//GEN-LAST:event_jlbEditStaffMouseClicked

    private void jrbSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSupervisorActionPerformed

    private void jlbAddStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAddStaffMouseClicked
        clear();
        duringCreate = true;
        jtfSearch.setEnabled(false);
        jtfSearch.setText("");
        calenderPanelstart.removeAll();
        calenderPanelstart.add(datePicker);
        repaint();

        jtfStaffID.setText(staffControl.getAfterLastCode());
        jtfStaffName.setEnabled(true);
        jtfUsername.setEnabled(true);
        jtfSalary.setEnabled(true);
        jtfNRIC.setEnabled(true);
        jtaAddress.setEnabled(true);
        jtfContactNum.setEnabled(true);
        jtfEmail.setEnabled(true);
        jtfAccNum.setEnabled(true);
        jrbDriver.setEnabled(true);
        jrbCounterClerk.setEnabled(true);
        jrbSupervisor.setEnabled(true);
        jrbManager.setEnabled(true);
        jcbBankType.setEnabled(true);
        jbtAdd.setVisible(true);
        jbtRemove.setVisible(true);
        jbtUpdate.setText("Create");
        jbtUpdate.setVisible(true);
    }//GEN-LAST:event_jlbAddStaffMouseClicked

    private void jlbSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSearchMouseClicked
        duringCreate = false;
        String id = jtfSearch.getText();
        Staff stf = staffControl.selectRecord(id);

        if (stf != null) {

            calenderPanelstart.removeAll();
            calenderPanelstart.add(jtfStartWorkDate);
            repaint();
            calenderPanelLast.removeAll();
            calenderPanelLast.add(jtfLastWorkDate);
            repaint();
            jtfStaffID.setText(stf.getStaffid());
            jtfStaffName.setText(stf.getStaffname());
            jtfUsername.setText(stf.getUsername());
            jtfSalary.setText("" + stf.getSalary());
            jtfNRIC.setText(stf.getNric());
            jtaAddress.setText(stf.getAddress());
            jtfContactNum.setText(stf.getContactno());
            jtfEmail.setText(stf.getEmail());
            jtfStartWorkDate.setText(stf.getFirstworkdate());
            jtfLastWorkDate.setText(stf.getLastworkdate());
            if (jtfLastWorkDate.getText().equals("") == true) {
                jtfLastWorkDate.setText("Current Staff");
            }
            jtfAccNum.setText(stf.getAccnumber());
            jtfSearch.setText("");
            if (stf.getJobposition().getJobposition().equals("Supervisor")) {
                jrbSupervisor.setEnabled(true);
                jrbSupervisor.setSelected(true);
            } else if (stf.getJobposition().getJobposition().equals("Counter Clerk")) {
                jrbCounterClerk.setSelected(true);
                jrbCounterClerk.setEnabled(true);
            } else if (stf.getJobposition().getJobposition().equals("Manager")) {
                jrbManager.setSelected(true);
                jrbManager.setEnabled(true);
            } else {
                jrbDriver.setSelected(true);
                jrbDriver.setEnabled(true);
            }
            for (int i = 0; i < jcbBankType.getItemCount(); i++) {
                if (stf.getPymtid().getPaymenttype().equals("" + jcbBankType.getItemAt(i))) {
                    jcbBankType.setSelectedItem(jcbBankType.getItemAt(i));
                }
            }
            imgPhoto = new ImageIcon(stf.getUrl());
            Image image = imgPhoto.getImage().getScaledInstance(129, 145, Image.SCALE_SMOOTH);
            imgPhoto.setImage(image);
            jlIcon.setIcon(imgPhoto);

        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID ", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jlbSearchMouseClicked

    private void jrbCounterClerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCounterClerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCounterClerkActionPerformed

    private void jcbBankTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBankTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBankTypeActionPerformed

    private void jtfContactNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactNumKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfContactNum.getText().length() < 11) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfContactNumKeyTyped

    private void jtfSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSalaryKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfSalary.getText().length() < 14) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfSalaryKeyTyped

    private void jtfUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetterOrDigit(c) && jtfUsername.getText().length() < 8) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfUsernameKeyTyped

    private void jtfStaffNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfStaffNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) && jtfStaffName.getText().length() < 100) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfStaffNameKeyTyped

    private void jtfStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStaffNameActionPerformed

    private void jtfStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStaffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStaffIDActionPerformed

    private void jlbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbClearActionPerformed
        clear();
    }//GEN-LAST:event_jlbClearActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        if (jbtUpdate.getText().equals("Create")) {
            Staff newStaff = null;

            Jobposition jobid;
            Paymenttype pymtid;

            double salary = Double.parseDouble(jtfSalary.getText());
            if (jrbSupervisor.isSelected()) {
                jobid = jobControl.selectRecordbyJob(jrbSupervisor.getText());
            } else if (jrbCounterClerk.isSelected()) {
                jobid = jobControl.selectRecordbyJob(jrbCounterClerk.getText());
            } else if (jrbManager.isSelected()) {
                jobid = jobControl.selectRecordbyJob(jrbManager.getText());
            } else {
                jobid = jobControl.selectRecordbyJob(jrbDriver.getText());

            }
            pymtid = paymentControl.selectRecordbyPayment("" + jcbBankType.getSelectedItem());
            try {

                newStaff = new Staff(jtfStaffID.getText(), jtfUsername.getText(),
                        "12345678", jtfStaffName.getText(), jtfNRIC.getText(), jobid,
                        salary, jtfContactNum.getText(), jtfEmail.getText(), jtaAddress.getText(),
                        datePicker.getJFormattedTextField().getText(), "-", pymtid,
                        jtfAccNum.getText(), "-", "-", imageURL);
                staffControl.addRecord(newStaff);
                if (jrbDriver.isSelected()) {
                    Driverlist driver = new Driverlist(driverlistControl.getAfterLastCode(), newStaff, "-", "AVAILABLE");
                    driverlistControl.addRecord(driver);
                    JOptionPane.showMessageDialog(null, driver.getDriid() + " is the driver ID for " + newStaff.getStaffid() + " : " + newStaff.getStaffname() + ".", "Insert to Database Success", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR in database", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, jtfStaffID.getText() + " Successfully Updated in Database!", "Update Success", JOptionPane.INFORMATION_MESSAGE);
            jtfSearch.setEnabled(true);
            clear();
            duringCreate = false;

        } else {

            String id = jtfStaffID.getText();
            Staff stf = staffControl.selectRecord(id);

            Jobposition jobid;
            Paymenttype pymtid;
            double salary = Double.parseDouble(jtfSalary.getText());
            stf.setStaffname(jtfStaffName.getText());
            stf.setUsername(jtfUsername.getText());
            stf.setSalary(salary);
            stf.setNric(jtfNRIC.getText());
            stf.setAddress(jtaAddress.getText());
            stf.setContactno(jtfContactNum.getText());
            stf.setEmail(jtfEmail.getText());
            stf.setLastworkdate("" + datePicker.getJFormattedTextField().getText());
            stf.setUrl(imageURL);
            if (jrbSupervisor.isSelected()) {
                jobid = jobControl.selectRecordbyJob(jrbSupervisor.getText());
            } else if (jrbCounterClerk.isSelected()) {
                jobid = jobControl.selectRecordbyJob(jrbCounterClerk.getText());
            } else if (jrbManager.isSelected()) {
                jobid = jobControl.selectRecordbyJob(jrbManager.getText());
            } else {
                jobid = jobControl.selectRecordbyJob(jrbDriver.getText());
                Driverlist driver = new Driverlist(driverlistControl.getAfterLastCode(), stf, "-", "Available");
                driverlistControl.addRecord(driver);
                JOptionPane.showMessageDialog(null, driver.getDriid() + " is the driver ID for " + stf.getStaffid() + " : " + stf.getStaffname() + ".", "Insert to Database Success", JOptionPane.INFORMATION_MESSAGE);
            }
            stf.setJobposition(jobid);
            pymtid = paymentControl.selectRecordbyPayment("" + jcbBankType.getSelectedItem());

            stf.setPymtid(pymtid);

            staffControl.updateRecord(stf);
            if (jrbDriver.isSelected()) {
                Driverlist driver = new Driverlist(driverlistControl.getAfterLastCode(), stf, "-", "AVAILABLE");
                driverlistControl.addRecord(driver);
                JOptionPane.showMessageDialog(null, driver.getDriid() + " is the driver ID for " + stf.getStaffid() + " : " + stf.getStaffname() + ".", "Insert to Database Success", JOptionPane.INFORMATION_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, jtfStaffID.getText() + " Successfully Updated in Database! ", "Insert to Database Success", JOptionPane.INFORMATION_MESSAGE);
            clear();
            jbtEndStaff.setVisible(false);
        }
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameActionPerformed
    public void clear() {
        jtfStaffID.setText("");
        jtfStaffName.setText("");
        jtfUsername.setText("");
        jtfSalary.setText("");
        jtfNRIC.setText("");
        jtaAddress.setText("");
        jtfContactNum.setText("");
        jtfEmail.setText("");
        jtfSearch.setText("");
        jtfAccNum.setText("");
        jtfStartWorkDate.setText("");
        jtfLastWorkDate.setText("");
        calenderPanelstart.removeAll();
        calenderPanelstart.add(jtfStartWorkDate);
        jtfStartWorkDate.removeAll();;
        jtfStartWorkDate.setEnabled(false);
        calenderPanelLast.removeAll();
        calenderPanelLast.add(jtfLastWorkDate);
        jtfLastWorkDate.setEnabled(false);
        repaint();
        jtfStaffName.setEnabled(false);
        jtfUsername.setEnabled(false);
        jtfSalary.setEnabled(false);
        jtfNRIC.setEnabled(false);
        jtaAddress.setEnabled(false);
        jtfContactNum.setEnabled(false);
        jtfEmail.setEnabled(false);
        jtfAccNum.setEnabled(false);
        jrbDriver.setEnabled(false);
        jrbCounterClerk.setEnabled(false);
        jrbSupervisor.setEnabled(false);
        jrbManager.setEnabled(false);
        jcbBankType.setEnabled(false);
        jbtAdd.setVisible(false);
        jbtRemove.setVisible(false);
        jbtUpdate.setText("Create");
        jbtUpdate.setVisible(false);
        jbtResetPassword.setVisible(false);
        jlIcon.setIcon(null);
        imageURL = "-";
        jtfSearch.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel calenderPanelLast;
    private javax.swing.JPanel calenderPanelstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtDriverSchedulling;
    private javax.swing.JButton jbtEndStaff;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JButton jbtResetPassword;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JComboBox jcbBankType;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlbAccNum;
    private javax.swing.JLabel jlbAddStaff;
    private javax.swing.JLabel jlbAddress;
    private javax.swing.JLabel jlbBankType;
    private javax.swing.JButton jlbClear;
    private javax.swing.JLabel jlbContactNum;
    private javax.swing.JLabel jlbEditStaff;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbLastWorkDate;
    private javax.swing.JLabel jlbNRIC;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbPosition;
    private javax.swing.JLabel jlbSalary;
    private javax.swing.JLabel jlbSearch;
    private javax.swing.JLabel jlbStaffID;
    private javax.swing.JLabel jlbStaffName;
    private javax.swing.JLabel jlbStartWorkDate;
    private javax.swing.JLabel jlbUsername;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JCheckBox jrbCounterClerk;
    private javax.swing.JCheckBox jrbDriver;
    private javax.swing.JCheckBox jrbManager;
    private javax.swing.JCheckBox jrbSupervisor;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextField jtfAccNum;
    private javax.swing.JTextField jtfContactNum;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNRIC;
    private javax.swing.JTextField jtfSalary;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JTextField jtfStaffName;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
