/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUSUI;

/**
 *
 * @author sooxl
 */
import BUSCONTROL.MaintainStaffControl;
import BUSDOMAIN.*;
import static BUSUI.MainUI.createImageIcon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

public class StaffPNCPanel extends javax.swing.JPanel {

    private Staff currentStaff;
    int count = 0;
    private MaintainStaffControl staffControl = new MaintainStaffControl();
    private JScrollPane JSPane;
    private JScrollPane jsContent;
    private JPanel jpBg = new JPanel(new BorderLayout());

    public StaffPNCPanel(Counter ds,Staff s) {
        initComponents();
        currentStaff=s;
        jlbStaffName.setText(currentStaff.getStaffname());
        jtfCurrentSQ.setText(currentStaff.getSecurityquestion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtfCurrentUsername = new javax.swing.JTextField();
        jlbRetypePW = new javax.swing.JLabel();
        jlbNewPassword = new javax.swing.JLabel();
        jlbCurrentPassword = new javax.swing.JLabel();
        jlbCurrentUsername = new javax.swing.JLabel();
        jlbStaffName = new javax.swing.JLabel();
        jlbHi = new javax.swing.JLabel();
        jbtUpdatePW = new javax.swing.JButton();
        jpfCurrentPW = new javax.swing.JPasswordField();
        jpfNewPW = new javax.swing.JPasswordField();
        jpfNewRetypePW = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jlbNewSQ = new javax.swing.JLabel();
        jlbNewSA = new javax.swing.JLabel();
        jlbCurrentSQ = new javax.swing.JLabel();
        jcbNewSecurityQuestion = new javax.swing.JComboBox();
        jtfNewSP = new javax.swing.JTextField();
        jbtUpdateSQ = new javax.swing.JButton();
        jtfCurrentSP = new javax.swing.JTextField();
        jlbCurrentSP = new javax.swing.JLabel();
        jtfCurrentSQ = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(0, 153, 153))); // NOI18N

        jtfCurrentUsername.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtfCurrentUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCurrentUsernameActionPerformed(evt);
            }
        });
        jtfCurrentUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCurrentUsernameKeyTyped(evt);
            }
        });

        jlbRetypePW.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbRetypePW.setText("Retype Password  :");

        jlbNewPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbNewPassword.setText("New Password      :");

        jlbCurrentPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentPassword.setText("Current Password :");

        jlbCurrentUsername.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentUsername.setText("Current Username:");

        jlbStaffName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlbStaffName.setForeground(new java.awt.Color(204, 0, 204));

        jlbHi.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlbHi.setForeground(new java.awt.Color(204, 0, 204));
        jlbHi.setText("Hi, ");

        jbtUpdatePW.setBackground(new java.awt.Color(192, 57, 43));
        jbtUpdatePW.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jbtUpdatePW.setForeground(new java.awt.Color(255, 255, 255));
        jbtUpdatePW.setText("Update");
        jbtUpdatePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdatePWActionPerformed(evt);
            }
        });

        jpfCurrentPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpfCurrentPWKeyTyped(evt);
            }
        });

        jpfNewPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpfNewPWKeyTyped(evt);
            }
        });

        jpfNewRetypePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfNewRetypePWActionPerformed(evt);
            }
        });
        jpfNewRetypePW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpfNewRetypePWKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jlbHi)
                        .addGap(18, 18, 18)
                        .addComponent(jlbStaffName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpfCurrentPW))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpfNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbCurrentUsername)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlbRetypePW, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jbtUpdatePW, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpfNewRetypePW, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbHi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbCurrentPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jpfCurrentPW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jpfNewPW))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbRetypePW)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jpfNewRetypePW, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtUpdatePW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Security Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        jlbNewSQ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbNewSQ.setText("New Security Question:");

        jlbNewSA.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbNewSA.setText("New Security Password:");

        jlbCurrentSQ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentSQ.setText("Current Security Question:");

        jcbNewSecurityQuestion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jcbNewSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is the middle name of your oldest child?", "What was your favorite sport in high school?", "Who is your childhood sports hero?", "What was the name of the company where you had your first job?", "What is your favorite movie?", "What was the name of the hospital where you were born?", "What is the first name of the boy or girl that you first kissed?", "What is the name of your favorite childhood friend?" }));
        jcbNewSecurityQuestion.setOpaque(false);

        jtfNewSP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtfNewSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNewSPKeyTyped(evt);
            }
        });

        jbtUpdateSQ.setBackground(new java.awt.Color(192, 57, 43));
        jbtUpdateSQ.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jbtUpdateSQ.setForeground(new java.awt.Color(255, 255, 255));
        jbtUpdateSQ.setText("Update");
        jbtUpdateSQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateSQActionPerformed(evt);
            }
        });

        jtfCurrentSP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtfCurrentSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCurrentSPKeyTyped(evt);
            }
        });

        jlbCurrentSP.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentSP.setText("Current Security Password:");

        jtfCurrentSQ.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtfCurrentSQ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCurrentSQ.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jbtUpdateSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlbCurrentSQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCurrentSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbNewSQ)
                                    .addComponent(jlbNewSA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNewSP, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbNewSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jlbCurrentSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCurrentSP, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCurrentSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCurrentSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCurrentSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCurrentSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbNewSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNewSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNewSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNewSA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtUpdateSQ))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCurrentUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCurrentUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCurrentUsernameActionPerformed

    private void jbtUpdatePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdatePWActionPerformed

        if (currentStaff != null && jpfCurrentPW.getText().equals(currentStaff.getPassword()) && jtfCurrentUsername.getText().equals(currentStaff.getUsername())) {
            if (jpfNewPW.getText().equals(jpfNewRetypePW.getText())) {
                count = 0;
                currentStaff.setPassword(jpfNewPW.getText());
                staffControl.updateRecord(currentStaff);
                JOptionPane.showMessageDialog(null, "New Password is updated!!", "Update Successfully", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "New Password and Retype Password does not match!", "Not Match", JOptionPane.ERROR_MESSAGE);
                jpfCurrentPW.setText("");
                jtfCurrentUsername.setText("");
                jpfNewPW.setText("");
                jpfNewRetypePW.setText("");
                closeProgram();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID or password", "Staff Not Found", JOptionPane.ERROR_MESSAGE);
            jpfCurrentPW.setText("");
            jtfCurrentUsername.setText("");
            jpfNewPW.setText("");
            jpfNewRetypePW.setText("");
            closeProgram();
        }
    }//GEN-LAST:event_jbtUpdatePWActionPerformed

    private void jpfNewRetypePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfNewRetypePWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfNewRetypePWActionPerformed

    private void jbtUpdateSQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateSQActionPerformed
        if (currentStaff != null && jtfCurrentSP.getText().equals(currentStaff.getSecuritypass())) {
            if (jtfNewSP.equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill in the Security Answer Field!", "Security Answer Field Empty", JOptionPane.ERROR_MESSAGE);
            } else {
                currentStaff.setSecurityquestion(jcbNewSecurityQuestion.getSelectedItem() + "");
                currentStaff.setSecuritypass(jtfNewSP.getText());
                staffControl.updateRecord(currentStaff);
                JOptionPane.showMessageDialog(null, "New Security Question is updated!!", "Update Successfully", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Security Answer", "Staff Not Found", JOptionPane.ERROR_MESSAGE);
            jtfCurrentSP.setText("");
            jtfNewSP.setText("");
            closeProgram();
        }
    }//GEN-LAST:event_jbtUpdateSQActionPerformed

    private void jtfCurrentUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCurrentUsernameKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetterOrDigit(c) && jtfCurrentUsername.getText().length() < 8) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfCurrentUsernameKeyTyped

    private void jpfCurrentPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfCurrentPWKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDefined(c) && jpfCurrentPW.getText().length() < 8) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jpfCurrentPWKeyTyped

    private void jtfCurrentSPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCurrentSPKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && jtfCurrentSP.getText().length() < 30) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfCurrentSPKeyTyped

    private void jtfNewSPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNewSPKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && jtfNewSP.getText().length() < 30) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfNewSPKeyTyped

    private void jpfNewPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfNewPWKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDefined(c) && jpfNewPW.getText().length() < 8) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jpfNewPWKeyTyped

    private void jpfNewRetypePWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfNewRetypePWKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDefined(c) && jpfNewRetypePW.getText().length() < 8) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jpfNewRetypePWKeyTyped
    public void closeProgram() {

        count++;
        if (count == 3) {
            JOptionPane.showMessageDialog(null, "You've typed the invalid username or password for 3 times!!!", "Closing Program...", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtUpdatePW;
    private javax.swing.JButton jbtUpdateSQ;
    private javax.swing.JComboBox jcbNewSecurityQuestion;
    private javax.swing.JLabel jlbCurrentPassword;
    private javax.swing.JLabel jlbCurrentSP;
    private javax.swing.JLabel jlbCurrentSQ;
    private javax.swing.JLabel jlbCurrentUsername;
    private javax.swing.JLabel jlbHi;
    private javax.swing.JLabel jlbNewPassword;
    private javax.swing.JLabel jlbNewSA;
    private javax.swing.JLabel jlbNewSQ;
    private javax.swing.JLabel jlbRetypePW;
    private javax.swing.JLabel jlbStaffName;
    private javax.swing.JPasswordField jpfCurrentPW;
    private javax.swing.JPasswordField jpfNewPW;
    private javax.swing.JPasswordField jpfNewRetypePW;
    private javax.swing.JTextField jtfCurrentSP;
    private javax.swing.JTextField jtfCurrentSQ;
    private javax.swing.JTextField jtfCurrentUsername;
    private javax.swing.JTextField jtfNewSP;
    // End of variables declaration//GEN-END:variables
}
